version: '3'
services:
  backend:
    environment:
      - MAX_RANDOM_PRECISION=25
      - REDIS_ENABLED=1
    build: .
    ports:
      - "8089:8089"
    links:
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
        - 6379:6379

